apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlq-consumer-ex4
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dlq-consumer-ex4
  template:
    metadata:
      labels:
        app: dlq-consumer-ex4
    spec:
      containers:
        - name: dlq-consumer
          image: app-ex4:latest
          imagePullPolicy: Never
          env:
            - name: APP_ROLE
              value: dlq_consumer
            - name: HEALTH_PORT
              value: "8082"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-credentials-ex4
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-credentials-ex4
                  key: RABBITMQ_PASS
          envFrom:
            - configMapRef:
                name: config-ex4
          ports:
            - name: health
              containerPort: 8082
          readinessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 20
