apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret-ex4
  namespace: default
type: Opaque
stringData:
  RABBITMQ_USER: tp3
  RABBITMQ_PASS: tp3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config-ex4
  namespace: default
data:
  RABBITMQ_HOST: rabbitmq-ex4
  RABBITMQ_PORT: "5672"
  MAIN_EXCHANGE: main_exchange
  MAIN_QUEUE: main_queue
  MAIN_ROUTING_KEY: tasks
  RETRY_EXCHANGE: retry_exchange
  RETRY_QUEUE: retry_queue
  RETRY_ROUTING_KEY: retry
  DLX_EXCHANGE: dlx_exchange
  DEAD_LETTER_QUEUE: dead_letter_queue
  DLQ_ROUTING_KEY: dead
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-ex4
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-ex4
  template:
    metadata:
      labels:
        app: rabbitmq-ex4
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret-ex4
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret-ex4
                  key: RABBITMQ_PASS
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ex4
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-ex4
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
