apiVersion: v1
kind: ConfigMap
metadata:
  name: config-ex3
  namespace: default
data:
  RABBITMQ_HOST: "rabbitmq-ex3"
  RABBITMQ_PORT: "5672"
  MAIN_EXCHANGE: "main_exchange"
  MAIN_QUEUE: "main_queue"
  MAIN_ROUTING_KEY: "tasks"
  DLX_EXCHANGE: "dlx_exchange"
  DEAD_LETTER_QUEUE: "dead_letter_queue"
  DLQ_ROUTING_KEY: "dead"
