events {}

http {
    # Definimos un grupo de servidores backend (los workers)
    upstream backend {
        server worker1:8000;
        server worker2:8000;
    }

    # Servidor frontal que escucha en el puerto 80
    server {
        listen 80;

        # Todas las peticiones se reparten entre los workers
        location / {
            proxy_pass http://backend;
        }
    }
}